[package]
name = "r-perms"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.10"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
clap = {version = "4.1", features = ["derive"]}
bbel-common = "0.1"